name: Test

on:
  push:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
        
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: cypress_w3_tests

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
